### ISSUE TITLE
got error starting Liberty server when run mvn install

### ISSUE THREAD

**Issue by ibmfjk** [OpenLiberty/guide-maven-intro#17]
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-runtime:null:17.0.0.3:zip.
[INFO] CWWKM2102I: Using installDirectory : /Users/fangjk/git/guide-maven-intro/start/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : ServletSampleServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/fangjk/git/guide-maven-intro/start/target/liberty/wlp/usr/servers/ServletSampleServer.
[Fatal Error] :9:45: The string "--" is not permitted within comments.
org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 45; The string "--" is not permitted within comments.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at net.wasdev.wlp.maven.plugins.ServerConfigDocument.parseDocument(ServerConfigDocument.java:295)
	at net.wasdev.wlp.maven.plugins.ServerConfigDocument.initializeAppsLocation(ServerConfigDocument.java:100)
	at net.wasdev.wlp.maven.plugins.ServerConfigDocument.<init>(ServerConfigDocument.java:66)
	at net.wasdev.wlp.maven.plugins.ServerConfigDocument.getInstance(ServerConfigDocument.java:86)
	at net.wasdev.wlp.maven.plugins.server.PluginConfigSupport.isAnyAppConfiguredInSourceServerXml(PluginConfigSupport.java:239)
	at net.wasdev.wlp.maven.plugins.server.PluginConfigSupport.getAppsDirectory(PluginConfigSupport.java:266)
	at net.wasdev.wlp.maven.plugins.server.PluginConfigSupport.exportParametersToXml(PluginConfigSupport.java:110)
	at net.wasdev.wlp.maven.plugins.server.PluginConfigSupport.installServerAssembly(PluginConfigSupport.java:70)
	at net.wasdev.wlp.maven.plugins.server.InstallServerMojo.doExecute(InstallServerMojo.java:30)
	at org.codehaus.mojo.pluginsupport.MojoSupport.execute(MojoSupport.java:122)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] CWWKM2185I: The liberty-maven-plugin configuration parameter "appsDirectory" value defaults to "dropins".
[INFO] CWWKM2112I: Re-using previously installed assembly.
[INFO] 
[INFO] --- liberty-maven-plugin:2.0:create-server (create-server) @ ServletSample ---

**Comment by JunyiSun** [comment]
This error is fixed by PR #13

**Comment by yeekangc** [comment]
@ibmfjk, please retry and let us know the results.
